name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.3.3
  - pip:
      - wandb==0.13.2
      - pandas==1.4.2
      - jupyterlab==3.0.12
      - pandas-profiling==3.1.0
      - pyarrow==2.0
      - Jinja2==3.1.1
      - seaborn==0.11.1
