name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - mlflow=1.28.0
  - cookiecutter=1.7.2
  - hydra-core=1.0.6
  - git=2.30.2
  - pip=20.3.3
  - pip:
      - jupyterlab==3.0.10
      - wandb==0.13.2
      - ipython==7.21.0
      - notebook==6.2.0
      - pandas==1.2.3
      - matplotlib==3.3.4
