name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - mlflow=1.28.0
  - pillow=8.1.2
  - pip:
      - scikit-learn==0.24.1
      - matplotlib==3.2.2
      - pandas==1.4.4
      - wandb==0.13.2
